[package]
name = "sand_evolution"
version = "0.1.0"
authors = ["wn"]
edition = "2021"

[[bin]]
name = "sand_evolution"
path = "src/main.rs"

[workspace]

[dependencies]
sand_evolution_lib = { path = "sand_evolution_lib" }
pollster = "0.2"